// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package org.dictionary;

public interface LockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isLocked = 1;</code>
   * @return The isLocked.
   */
  boolean getIsLocked();
}
