// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package org.dictionary;

public final class LockProto {
  private LockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nlock.proto\032\ttxn.proto\"\030\n\004Lock\022\020\n\010isLoc" +
      "ked\030\001 \001(\0102=\n\013LockService\022\025\n\004lock\022\006.TxnKV" +
      "\032\005.Lock\022\027\n\006unlock\022\006.TxnKV\032\005.LockB\035\n\016org." +
      "dictionaryB\tLockProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.dictionary.TxnProto.getDescriptor(),
        });
    internal_static_Lock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Lock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lock_descriptor,
        new java.lang.String[] { "IsLocked", });
    org.dictionary.TxnProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
