// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package org.dictionary;

public interface TxnKVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TxnKV)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>.Txn txn = 4;</code>
   * @return Whether the txn field is set.
   */
  boolean hasTxn();
  /**
   * <code>.Txn txn = 4;</code>
   * @return The txn.
   */
  org.dictionary.Txn getTxn();
  /**
   * <code>.Txn txn = 4;</code>
   */
  org.dictionary.TxnOrBuilder getTxnOrBuilder();
}
