// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package org.dictionary;

public interface TxnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Txn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string txn = 1;</code>
   * @return The txn.
   */
  java.lang.String getTxn();
  /**
   * <code>string txn = 1;</code>
   * @return The bytes for txn.
   */
  com.google.protobuf.ByteString
      getTxnBytes();
}
